# Generated by Django 5.1.4 on 2024-12-20 17:55

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('country', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(56)])),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('trip_category', models.CharField(choices=[('Leisure', 'LEISURE'), ('Business', 'BUSINESS'), ('Adventure', 'ADVENTURE'), ('Family', 'FAMILY'), ('Romantic', 'ROMANTIC')], default='LEISURE', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('trip_status', models.CharField(choices=[('Completed', 'COMPLETED'), ('Ongoing', 'ONGOING'), ('Planned', 'PLANNED')], default='PLANNED', max_length=50)),
                ('shared', models.CharField(choices=[('Yes', 'YES'), ('NO', 'No')], default='YES', max_length=3)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on', 'country', 'start_date'],
            },
        ),
    ]
