# Generated by Django 5.1.4 on 2024-12-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_rename_follows_profile_following_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='follows',
        ),
    ]
