# Generated by Django 5.1.4 on 2024-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../image/upload/v1728892217/tsipho0ghipyymo9gs9s.webp', upload_to='images/'),
        ),
    ]
