# Generated by Django 5.1.4 on 2024-12-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/image/upload/v1734277998/tsipho0ghipyymo9gs9s_veaxrw.webp', upload_to='images/'),
        ),
    ]
